// scripts/set-env.mjs
// Auto-generates src/environments/api-key.ts from .env.local or system env vars

import { writeFileSync, mkdirSync, readFileSync } from 'fs';

// Manually parse .env.local (no dotenv required)
try {
  const envContent = readFileSync('.env.local', 'utf8');
  for (const line of envContent.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
    if (key && !process.env[key]) {
      process.env[key] = value;
    }
  }
} catch {
  // .env.local not found — using system/Vercel env vars
}

const apiKey = process.env.GEMINI_API_KEY || '';

mkdirSync('src/environments', { recursive: true });

writeFileSync(
  'src/environments/api-key.ts',
  `// Auto-generated by scripts/set-env.mjs — do not edit manually\nexport const API_KEY = ${JSON.stringify(apiKey)};\n`
);

console.log(`✅ Environment file generated. API_KEY: ${apiKey ? '***set***' : '⚠️  MISSING — set GEMINI_API_KEY env var'}`);
